import type { Metadata } from "next";
import { Inter, Merriweather } from "next/font/google";
import "./globals.css";
import Provider from "../components/Provider/Provider";
import { Suspense } from "react";
import LoadingPage from "@/components/Loading";
const inter = Inter({ subsets: ["latin"] });
const merriweather= Merriweather(
  {
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',

  }
);

export const metadata: Metadata = {
  title: "Concept Mapper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <Suspense fallback={<LoadingPage/>} >
    <Provider>
      <html lang="en">
      <body className={`${inter.className} ${merriweather.className}`}>
          {children}</body>
      </html>
    </Provider>
    // </Suspense>
  );
}
